.DEFAULT_GOAL := help

build:## crear una imagen: make build
	docker build -f ./Dockerfile -t imagen--demo-creada:1.0 .

run:## ejecutar la imagen odcker: make run
	docker run -it imagen--demo-creada:1.0

## Target Help ##
help:
	@printf "\033[31m%-16s %-59s %s\033[0m\n" "Target" "Help" "Usage"; \
	printf "\033[31m%-16s %-59s %s\033[0m\n" "------" "----" "-----"; \
	grep -hE '^\S+:.*## .*$$' $(MAKEFILE_LIST) | sed -e 's/:.*##\s*/:/' | sort | awk 'BEGIN {FS = ":"}; {printf "\033[32m%-16s\033[0m %-58s \033[34m%s\033[0m\n", $$1, $$2, $$3}'
	